export const ACTION_GET_CARS_STARTED = "GET_CARS_STARTED";
export const ACTION_GET_CARS_SUCCESS = "GET_CARS_SUCCESS";

export const ACTION_POST_CARS_SUCCESS = "POST_CARS_SUCCESS";
export const ACTION_POST_CARS_STARTED = "POST_CARS_STARTED";

export const ADD_CAR = 'ADD_CAR';
export const DELETE_CAR = 'DELETE_CAR';
export const FETCH_CAR = 'FETCH_CAR';